name = "Babric Enriched"
author = "DanyGames2014"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "774d38245db4e140679db5b8043bc28333f895386c3599a9a96358dfb93d39fa"

[versions]
fabric = "0.17.2"
minecraft = "b1.7.3"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["b1.7.3"]
