name = "Babric Enriched"
author = "DanyGames2014"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6816344a96d5f73115d549defe196061d121f79492d82338a789521970737e52"

[versions]
fabric = "0.19.2"
minecraft = "b1.7.3"
unsup = "1.2.4"

[options]
acceptable-game-versions = ["b1.7.3"]
