name = "Babric Enriched"
author = "DanyGames2014"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a28a1468874cd1897304996ffc4f49d55e53aa1198997336134c2556731edd9"

[versions]
fabric = "0.19.2"
minecraft = "b1.7.3"
unsup = "1.2.4"

[options]
acceptable-game-versions = ["b1.7.3"]
